# Generated by Django 5.2.2 on 2025-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Offer Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Brief Offer Description')),
                ('image', models.ImageField(blank=True, upload_to='daily_offers/%Y/%m/%d/', verbose_name='Offer Image')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='Product/Offer Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Offer',
                'verbose_name_plural': 'Daily Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
