# Generated by Django 5.2.2 on 2025-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, help_text='e.g., New, Used: Grade A, Refurbished', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, help_text='e.g., Intel Core i3-1005G1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(blank=True, help_text='e.g., Business, Gaming, 2-in-1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, help_text='e.g., Intel Iris Plus G1, NVIDIA GeForce RTX 3050', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keyboard_language',
            field=models.CharField(blank=True, help_text='e.g., EN, AR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, help_text='Specific model name (e.g., Inspiron 3501)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Original price before discount (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g., 8GB, 16GB DDR4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, help_text='e.g., 60Hz, 120Hz', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='e.g., 1920x1080, 1366x768', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, help_text='e.g., 15.6 inch, 13.3 inch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g., 128GB, 512GB SSD, 1TB HDD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_config',
            field=models.CharField(blank=True, help_text='e.g., 128GB SSD, 512GB NVMe SSD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='e.g., 3 Months, 1 Year', max_length=100, null=True),
        ),
    ]
