# Generated by Django 5.2.2 on 2025-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_condition_product_cpu_product_form_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished'), ('OPEN_BOX', 'Open Box'), ('DAMAGED', 'Damaged')], help_text='e.g., New, Used: Grade A, Refurbished', max_length=50, null=True),
        ),
    ]
