# Generated by Django 5.2.2 on 2025-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished'), ('OPEN_BOX', 'Open Box'), ('ESTERAD', 'Esterad')], help_text='e.g., New, Used: Grade A, Refurbished', max_length=50, null=True),
        ),
    ]
