# Generated by Django 5.2.2 on 2025-06-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping addresses'},
        ),
    ]
