# Generated by Django 5.2.2 on 2025-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orderitem_price_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
    ]
