# Generated by Django 5.2.2 on 2025-06-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='cart.cart'),
        ),
    ]
