# Generated by Django 5.2.2 on 2025-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
